// <auto-generated />
using System;
using ExpenseGuard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseGuard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004202757_IT24103356SharedPlatformFoundation")]
    partial class IT24103356SharedPlatformFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalProcess", b =>
                {
                    b.Property<Guid>("ApprovalProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalWorkflowTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("integer");

                    b.Property<int>("ReimbursementId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalProcessId");

                    b.HasIndex("ApprovalWorkflowTemplateId");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("ApprovalProcesses");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalStageDefinition", b =>
                {
                    b.Property<int>("ApprovalStageDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalStageDefinitionId"));

                    b.Property<int>("ApprovalWorkflowTemplateId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaximumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinimumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("ApprovalStageDefinitionId");

                    b.HasIndex("ApprovalWorkflowTemplateId", "Sequence")
                        .IsUnique();

                    b.ToTable("ApprovalStageDefinitions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalStep", b =>
                {
                    b.Property<Guid>("ApprovalStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DecidedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("StageSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalStepId");

                    b.HasIndex("DecidedByEmployeeId");

                    b.HasIndex("ApprovalProcessId", "Sequence")
                        .IsUnique();

                    b.ToTable("ApprovalSteps");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", b =>
                {
                    b.Property<int>("ApprovalWorkflowTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalWorkflowTemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalWorkflowTemplateId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ApprovalWorkflowTemplates");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuditLogId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetId"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("SpentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("BudgetId");

                    b.HasIndex("DepartmentId", "Period")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ExpenseClaim", b =>
                {
                    b.Property<int>("ExpenseClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpenseClaimId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PurchaseNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReceiptDoc")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptImg")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExpenseClaimId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Status");

                    b.ToTable("ExpenseClaims");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.FraudFlag", b =>
                {
                    b.Property<int>("FraudFlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FraudFlagId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("FlagReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("FraudFlagId");

                    b.HasIndex("ExpenseClaimId");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReimbursementId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ReimbursementId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicyId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("ReceiptRequired")
                        .HasColumnType("boolean");

                    b.HasKey("PolicyId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Reimbursement", b =>
                {
                    b.Property<int>("ReimbursementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReimbursementId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentProvider")
                        .HasColumnType("text");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReimbursementId");

                    b.HasIndex("ExpenseClaimId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Reimbursements");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<decimal>("ApprovalLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("CanApprove")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageRoles")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanProcessPayments")
                        .HasColumnType("boolean");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            ApprovalLimit = 0m,
                            CanApprove = false,
                            CanManageRoles = false,
                            CanProcessPayments = false,
                            PermissionsJson = "[\"reimbursement:self\"]",
                            RoleName = "Employee"
                        },
                        new
                        {
                            RoleId = 2,
                            ApprovalLimit = 100000m,
                            CanApprove = true,
                            CanManageRoles = false,
                            CanProcessPayments = false,
                            PermissionsJson = "[\"reimbursement:approve\"]",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            ApprovalLimit = 1000000m,
                            CanApprove = true,
                            CanManageRoles = false,
                            CanProcessPayments = false,
                            PermissionsJson = "[\"reimbursement:approve\"]",
                            RoleName = "DepartmentHead"
                        },
                        new
                        {
                            RoleId = 4,
                            ApprovalLimit = 0m,
                            CanApprove = false,
                            CanManageRoles = false,
                            CanProcessPayments = true,
                            PermissionsJson = "[\"payment:process\"]",
                            RoleName = "Finance"
                        },
                        new
                        {
                            RoleId = 5,
                            ApprovalLimit = 9999999999999999.99m,
                            CanApprove = true,
                            CanManageRoles = true,
                            CanProcessPayments = true,
                            PermissionsJson = "[\"*\"]",
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ToolExecution", b =>
                {
                    b.Property<Guid>("ToolExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("RequestJson")
                        .HasColumnType("text");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.HasKey("ToolExecutionId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("ToolExecutions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ValidationResult", b =>
                {
                    b.Property<Guid>("ValidationResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Validator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.HasKey("ValidationResultId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("ValidationResults");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowExecution", b =>
                {
                    b.Property<Guid>("WorkflowExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkflowExecutionId");

                    b.HasIndex("ExpenseClaimId");

                    b.ToTable("WorkflowExecutions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowStep", b =>
                {
                    b.Property<Guid>("WorkflowStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputSnapshotJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputSnapshotJson")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkflowStepId");

                    b.HasIndex("WorkflowExecutionId");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalProcess", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseGuard.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("ApprovalProcesses")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reimbursement");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalStageDefinition", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", "Template")
                        .WithMany("Stages")
                        .HasForeignKey("ApprovalWorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalStep", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ApprovalProcess", "ApprovalProcess")
                        .WithMany("Steps")
                        .HasForeignKey("ApprovalProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseGuard.Api.Models.Employee", "DecidedByEmployee")
                        .WithMany()
                        .HasForeignKey("DecidedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovalProcess");

                    b.Navigation("DecidedByEmployee");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.AuditLog", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Budget", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Department", "Department")
                        .WithMany("Budgets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Employee", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseGuard.Api.Models.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ExpenseGuard.Api.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ExpenseClaim", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Employee", "Employee")
                        .WithMany("ExpenseClaims")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.FraudFlag", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithMany("FraudFlags")
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PaymentTransaction", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Policy", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Department", "Department")
                        .WithMany("Policies")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Reimbursement", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithOne("Reimbursement")
                        .HasForeignKey("ExpenseGuard.Api.Models.Reimbursement", "ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ToolExecution", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.WorkflowStep", "WorkflowStep")
                        .WithMany("ToolExecutions")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ValidationResult", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.WorkflowStep", "WorkflowStep")
                        .WithMany("ValidationResults")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowExecution", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithMany()
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowStep", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.WorkflowExecution", "WorkflowExecution")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowExecution");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalProcess", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Department", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Employees");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("ExpenseClaims");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ExpenseClaim", b =>
                {
                    b.Navigation("FraudFlags");

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Reimbursement", b =>
                {
                    b.Navigation("ApprovalProcesses");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowExecution", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowStep", b =>
                {
                    b.Navigation("ToolExecutions");

                    b.Navigation("ValidationResults");
                });
#pragma warning restore 612, 618
        }
    }
}
